apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
    project: hello-app-project
  name: hello-app
  namespace: hello-app
spec:
  ports:
  - port: {{.Values.appPorts.servicePort}}
    protocol: TCP
    targetPort: {{.Values.appPorts.containerPort}}
  selector:
    app: hello-app
  sessionAffinity: None
  type: ClusterIP
