apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-app
    project: hello-app-project
  name: hello-app
  namespace: hello-app
spec:
  ports:
  - port: 8010
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-app
  sessionAffinity: None
  type: ClusterIP
